import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Button, Layout, Menu, MenuProps } from 'antd'
import { Content, Header } from 'antd/es/layout/layout'
import Sider from 'antd/es/layout/Sider'
import { useState } from 'react'
import { UploadOutlined, UserOutlined, VideoCameraOutlined } from '@ant-design/icons'
import { apolloClient } from '@/graphql/main'
import { ApolloProvider } from '@apollo/client'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const siderList = ['Биржа', 'Исполнители','Заказчики', 'Документы ']

const items1: MenuProps['items'] = siderList.map((key) => ({
  key,
  label: key,
}));


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body className={inter.className}>
            {children}
        </body>
    </html>
  )
}
